name: LucifersEssentials
version: 1.0
main: tk.jacobcraft.lucifersplugin.Main
api-version: 1.16
authors: [ Torchwood1#4320, SamTiz#0913 ]
description: a simple helloworld plugin!
website: com.midlandwebmasters.jacobempire.HelloWorld

commands:
  rank:
    description: allows a staff member to set a players rank
    permission: test.rank

  tpall:
    description: Teleports all the players to your location
    permission: test.tpall

  tp:
    description: Telleports players
    permission: test.tp

  gamemode:
    permission: test.gamemode
    description: changes your gamemode
    aliases: [gms, gmc, gmsp, creative, gm, survival, spectator, 1, 3,0]

  vanish:
    permission: test.vanish
    description: vanishes you from the world
    aliases: [v]

  feed:
    permission: test.feed
    permission-message: ยง4You are not authorised
    aliases: [hunger,unstarve,feed]
    description: it feeds you, pretty simple really!

  stick:
    aliases: [stickoftruth,painstick,lucifersfury]
    description: this is an epic weapon for Lucifer

  fly:
    permission: test.fly
    permission-message: ยง4you are not authorised, get recked!
    aliases: [soar,fallwithstyle,levitate,hover]
    description: this allows you to fly, pretty simple really

  helloworld:
    permission: test.helloworld
    permission-message: ยง4you are not authorised, get recked!
    aliases: [hi,hello]
    description: This is the hello command!

  time:
    aliases:
      - day
      - night
      - noon
      - midnight
    usage: "/<command> [day|night|noon|midnight|ticks]"
    permission: test.time

  weather:
    aliases:
      - sun
      - rain
      - snow
    usage: "/<command> [rain|sun]"
    permission: test.weather

  echest:
    aliases:
      - endersee
      - ec
      - envsee
      - endermanbox
      - enderchest
    permission: test.echest
    usage: "/<command> [player]"

  invsee:
    aliases:
      - openinv
      - seeinv
      - armorsee
    permission: test.invsee
    usage: "/<command> [player]"

  world:
    permission: test.world
    description: allows you to change world!

  hacks:
    permission: test.hacks
    description: built in hacks for players to use :)



permissions:
  test.rank.override:
    default: op
    description: this command node allows the authorised people to change anyone's rank

  test.rank:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /rank

  test.gamemode:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /gamemode or aliases

  test.vanish:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /vanish or aliases
  test.vanish.others:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /vanish or aliases on others
  test.vanish.*:
    children:
      test.vanish: true
      test.vanish.others: true
    description: a simple command node to allow authorised peoople to use the epic command /vanish or aliases to it's full extent
    default: op

  test.feed:
    default: op
    description: a simple command node to allow authorised people to use the epic command /feed or aliases

  test.fly:
    default: op
    description: a simple command node to allow autorised people to use the epic command /fly or aliases

  test.helloworld:
    default: op
    description: a simple command node to allow people to use the epic command /helloworld or aliases

  test.time:
    default: true
    description: "Allows you to use /time"

  test.time.set:
    default: false
    description: "Allows you to use /time set"
    children: [ test.time ]

  test.weather:
    default: true
    description: "Allows you to use /weather"

  test.weather.set:
    default: op
    description: "Allows you to use /weather set"
    children: [ test.weather ]

  test.tpall:
    default: op
    description: "Allows you to use /tp all players"

  test.tp:
    default: op
    description: "Allows you to use /tp"

  test.echest:
  default: true
  description: "Allows you to use /echest"

  test.echest.others:
    default: op
    description: "Allows you to see other people's enderchests"

  test.echest.*:
    children:
      - test.echest
      - test.echest.others

  test.invsee:
    default: true
    description: "Allows you to use /invsee"

  test.invsee.others:
    default: op
    description: "Allows you to see other people's inventories"

  test.invsee.armor:
    default: op
    description: "Allows you to use /armorsee"

  test.invsee.*:
    children:
      - test.invsee
      - test.invsee.others
      - test.invsee.armor

  test.world:
    default: op
    description: "Allows you to use /world"

  test.hacks:
    default: op
    description: "Allows you to use /hacks"

  test.*:
    default: op
    children:
      test.rank.override: true
      test.rank: true
      test.tp: true
      test.tpall: true
      test.vanish.*: true
      test.fly: true
      test.helloworld: true
      test.feed: true
      test.weather.set: true
      test.time.set: true
      test.invsee.*: true
      test.echest.*: true
      test.hacks: true
    description: this allows a person to use all commands
