name: LucifersEssentials
version: 1.0
main: tk.jacobcraft.lucifersplugin.Main
api-version: 1.16
authors: [ Torchwood1#4320, SamTiz#0913 ]
description: a simple helloworld plugin!
website: com.midlandwebmasters.jacobempire.HelloWorld

commands:
  rank:
    description: allows a staff member to set a players rank
    permission: test.rank

  tpall:
    description: Teleports all the players to your location
    permission: test.tpall

  tp:
    description: Telleports players
    permission: test.tp

  gamemode:
    permission: luciferessentials.gamemode
    description: changes your gamemode
    aliases: [gms, gmc, gmsp, creative, gm, survival, spectator, 1, 3,0]

  vanish:
    permission: luciferessentials.vanish
    description: vanishes you from the world
    aliases: [v]

  heal:
    permission: luciferessentials.heal
    description: Heals people with permission

  feed:
    permission: luciferessentials.feed
    permission-message: ยง4You are not authorised
    aliases: [hunger,unstarve,feed]
    description: it feeds you, pretty simple really!

  stick:
    aliases: [stickoftruth,painstick,lucifersfury]
    description: this is an epic weapon for Lucifer

  fly:
    permission: luciferessentials.fly
    permission-message: ยง4you are not authorised, get recked!
    aliases: [soar,fallwithstyle,levitate,hover]
    description: this allows you to fly, pretty simple really

  helloworld:
    permission: luciferessentials.helloworld
    permission-message: ยง4you are not authorised, get recked!
    aliases: [hi,hello]
    description: This is the hello command!

  time:
    aliases:
      - day
      - night
      - noon
      - midnight
    usage: "/<command> [day|night|noon|midnight|ticks]"
    permission: luciferessentials.time
    description: allows you to change the time

  weather:
    aliases:
      - sun
      - rain
      - snow
    usage: "/<command> [rain|sun]"
    permission: luciferessentials.weather
    description: allows you to change the weather

  echest:
    aliases:
      - endersee
      - ec
      - envsee
      - endermanbox
      - enderchest
    permission: luciferessentials.echest
    usage: "/<command> [player]"
    description: allows you to look in enderchests

  invsee:
    aliases:
      - openinv
      - seeinv
      - armorsee
    permission: luciferessentials.invsee
    usage: "/<command> [player]"
    description: allows you to look in people's inventoryies

  world:
    permission: luciferessentials.world
    description: allows you to change world!

  hacks:
    permission: luciferessentials.hacks
    description: built in hacks for players to use :)



permissions:
  luciferessentials.rank.override:
    default: op
    description: this command node allows the authorised people to change anyone's rank

  luciferessentials.rank:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /rank

  luciferessentials.gamemode:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /gamemode or aliases

  luciferessentials.vanish:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /vanish or aliases
  luciferessentials.vanish.others:
    default: op
    description: a simple command node to allow the authorised people to use the epic command /vanish or aliases on others
  luciferessentials.vanish.*:
    children:
      test.vanish: true
      test.vanish.others: true
    description: a simple command node to allow authorised peoople to use the epic command /vanish or aliases to it's full extent
    default: op

  luciferessentials.heal:
    default: op
    description: a simple command node to allow authorised people to use the epic command /heal

  luciferessentials.feed:
    default: op
    description: a simple command node to allow authorised people to use the epic command /feed or aliases

  luciferessentials.fly:
    default: op
    description: a simple command node to allow autorised people to use the epic command /fly or aliases

  luciferessentials.helloworld:
    default: op
    description: a simple command node to allow people to use the epic command /helloworld or aliases

  luciferessentials.time:
    default: true
    description: "Allows you to use /time"

  luciferessentials.time.set:
    default: false
    description: "Allows you to use /time set"
    children: [ test.time ]

  luciferessentials.weather:
    default: true
    description: "Allows you to use /weather"

  luciferessentials.weather.set:
    default: op
    description: "Allows you to use /weather set"
    children: [ test.weather ]

  luciferessentials.tpall:
    default: op
    description: "Allows you to use /tp all players"

  luciferessentials.tp:
    default: op
    description: "Allows you to use /tp"

  luciferessentials.echest:
  default: true
  description: "Allows you to use /echest"

  luciferessentials.echest.others:
    default: op
    description: "Allows you to see other people's enderchests"

  luciferessentials.echest.*:
    children:
      - test.echest
      - test.echest.others

  luciferessentials.invsee:
    default: true
    description: "Allows you to use /invsee"

  luciferessentials.invsee.others:
    default: op
    description: "Allows you to see other people's inventories"

  luciferessentials.invsee.armor:
    default: op
    description: "Allows you to use /armorsee"

  luciferessentials.invsee.*:
    description: allows you to look in other people's inventoryies
    children:
    - test.invsee
    - test.invsee.others
    - test.invsee.armor

  luciferessentials.world:
    default: op
    description: "Allows you to use /world"

  test.hacks:
    default: op
    description: "Allows you to use /hacks"

  luciferessentials.*:
    default: op
    children:
      luciferessentials.rank.override: true
      luciferessentials.rank: true
      luciferessentials.tp: true
      luciferessentials.tpall: true
      luciferessentials.vanish.*: true
      luciferessentials.fly: true
      luciferessentials.helloworld: true
      luciferessentials.feed: true
      luciferessentials.heal: true
      luciferessentials.weather.set: true
      luciferessentials.time.set: true
      luciferessentials.invsee.*: true
      luciferessentials.echest.*: true
      luciferessentials.hacks: true
    description: this allows a person to use all commands
